### ISSUE TITLE
java.lang.IllegalArgumentException: Allocation size must be greater than zero

### ISSUE THREAD

**Issue by oncecrossover** [brevilo/jolm#13]
Hey @brevilo ,

I'm back again, we got a new error, could you check and fix it?

**Describe the bug**

```
java.lang.IllegalArgumentException: Allocation size must be greater than zero
        at com.sun.jna.Memory.<init>(Memory.java:239)
        at io.github.brevilo.jolm.Utils.toNative(Utils.java:86)
        at io.github.brevilo.jolm.Session.createInboundSession(Session.java:341)
        at net.metachain.server.utils.OlmCryptoUtils.decrypt(OlmCryptoUtils.java:69)
        at net.metachain.server.service.impl.NetworkServiceImpl.findCachedNodes(NetworkServiceImpl.java:402)
        at net.metachain.server.service.impl.PCClientServiceImpl.syncNodesV2(PCClientServiceImpl.java:361)
        at net.metachain.server.service.impl.PCClientServiceImpl$$FastClassBySpringCGLIB$$7cb9ffc5.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at net.metachain.server.service.impl.PCClientServiceImpl$$EnhancerBySpringCGLIB$$87212b8.syncNodesV2(<generated>)
        at net.metachain.server.controller.PCClientController.syncNodes(PCClientController.java:45)
        at sun.reflect.GeneratedMethodAccessor283.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
                                                                                                                                                                                              2512,1-8       7%
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at net.metachain.server.common.filter.OlmResponseFilter.doFilterInternal(OlmResponseFilter.java:34)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at net.metachain.server.common.filter.HttpRequestFilter.doFilterInternal(HttpRequestFilter.java:48)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                                                                                                                                                                                              2551,2-9       8%
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
Should not happen this error.

**To Reproduce**
With many request, some times, it will reproduce.

**Environment (please complete the following information):**
 - OS: Linux
 - Java version: openjdk version "1.8.0_292"
 - libolm version 3.2.6
 - jOlm version 1.0.4

**Comment by brevilo** [comment]
Hi!

This says it pretty much:
```
java.lang.IllegalArgumentException: Allocation size must be greater than zero
        at com.sun.jna.Memory.<init>(Memory.java:239)
        at io.github.brevilo.jolm.Utils.toNative(Utils.java:86)
        at io.github.brevilo.jolm.Session.createInboundSession(Session.java:341)
        at net.metachain.server.utils.OlmCryptoUtils.decrypt(OlmCryptoUtils.java:69)
```
Your `oneTimeKeyMessage` argument is empty. jOlm's error handling philosophy at this time is to throw exceptions instead of checking for each an every error condition explicitly. That said, you either need to check your arguments before you pass them to jOlm or catch the exceptions it throws.

**Comment by oncecrossover** [comment]
> Hi!
> 
> This says it pretty much:
> 
> ```
> java.lang.IllegalArgumentException: Allocation size must be greater than zero
>         at com.sun.jna.Memory.<init>(Memory.java:239)
>         at io.github.brevilo.jolm.Utils.toNative(Utils.java:86)
>         at io.github.brevilo.jolm.Session.createInboundSession(Session.java:341)
>         at net.metachain.server.utils.OlmCryptoUtils.decrypt(OlmCryptoUtils.java:69)
> ```
> 
> Your `oneTimeKeyMessage` argument is empty. jOlm's error handling philosophy at this time is to throw exceptions instead of checking for each an every error condition explicitly. That said, you either need to check your arguments before you pass them to jOlm or catch the exceptions it throws.

Got it！I have fixed and tested it, thanks bro!
